<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit3e562bcac07636e66bb1ea90cd07a99e
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'DeepL\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'DeepL\\' => 
        array (
            0 => __DIR__ . '/..' . '/deeplcom/deepl-php/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit3e562bcac07636e66bb1ea90cd07a99e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit3e562bcac07636e66bb1ea90cd07a99e::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit3e562bcac07636e66bb1ea90cd07a99e::$classMap;

        }, null, ClassLoader::class);
    }
}
